# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: balanceador.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='balanceador.proto',
  package='problema2_1',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x62\x61lanceador.proto\x12\x0bproblema2_1\"\x17\n\tReqServer\x12\n\n\x02ip\x18\x01 \x01(\t\"\"\n\tResServer\x12\x15\n\rhost_servidor\x18\x01 \x01(\t2B\n\x04\x44\x61ta\x12:\n\x06Server\x12\x16.problema2_1.ReqServer\x1a\x16.problema2_1.ResServer\"\x00\x62\x06proto3'
)




_REQSERVER = _descriptor.Descriptor(
  name='ReqServer',
  full_name='problema2_1.ReqServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='problema2_1.ReqServer.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=57,
)


_RESSERVER = _descriptor.Descriptor(
  name='ResServer',
  full_name='problema2_1.ResServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host_servidor', full_name='problema2_1.ResServer.host_servidor', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['ReqServer'] = _REQSERVER
DESCRIPTOR.message_types_by_name['ResServer'] = _RESSERVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqServer = _reflection.GeneratedProtocolMessageType('ReqServer', (_message.Message,), {
  'DESCRIPTOR' : _REQSERVER,
  '__module__' : 'balanceador_pb2'
  # @@protoc_insertion_point(class_scope:problema2_1.ReqServer)
  })
_sym_db.RegisterMessage(ReqServer)

ResServer = _reflection.GeneratedProtocolMessageType('ResServer', (_message.Message,), {
  'DESCRIPTOR' : _RESSERVER,
  '__module__' : 'balanceador_pb2'
  # @@protoc_insertion_point(class_scope:problema2_1.ResServer)
  })
_sym_db.RegisterMessage(ResServer)



_DATA = _descriptor.ServiceDescriptor(
  name='Data',
  full_name='problema2_1.Data',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=95,
  serialized_end=161,
  methods=[
  _descriptor.MethodDescriptor(
    name='Server',
    full_name='problema2_1.Data.Server',
    index=0,
    containing_service=None,
    input_type=_REQSERVER,
    output_type=_RESSERVER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATA)

DESCRIPTOR.services_by_name['Data'] = _DATA

# @@protoc_insertion_point(module_scope)
