# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servidor_n.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='servidor_n.proto',
  package='problema2_2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10servidor_n.proto\x12\x0bproblema2_2\"\'\n\x0bReqServidor\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\"\'\n\x0bReqConexion\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\"\x1b\n\tReqSaludo\x12\x0e\n\x06nombre\x18\x01 \x01(\t\"R\n\x0bResConexion\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x10\n\x08\x63onexion\x18\x02 \x01(\x08\x12\x12\n\nconexiones\x18\x03 \x01(\x05\x12\x0f\n\x07mensaje\x18\x04 \x01(\t\"\x1b\n\tResSaludo\x12\x0e\n\x06saludo\x18\x01 \x01(\t2\xa0\x02\n\x04\x44\x61ta\x12J\n\x12ServidorConexiones\x12\x18.problema2_2.ReqServidor\x1a\x18.problema2_2.ResConexion\"\x00\x12G\n\x0f\x43onexionExitosa\x12\x18.problema2_2.ReqConexion\x1a\x18.problema2_2.ResConexion\"\x00\x12;\n\x07MSaludo\x12\x16.problema2_2.ReqSaludo\x1a\x16.problema2_2.ResSaludo\"\x00\x12\x46\n\x0eRemoveConexion\x12\x18.problema2_2.ReqConexion\x1a\x18.problema2_2.ResConexion\"\x00\x62\x06proto3'
)




_REQSERVIDOR = _descriptor.Descriptor(
  name='ReqServidor',
  full_name='problema2_2.ReqServidor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='problema2_2.ReqServidor.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tipo', full_name='problema2_2.ReqServidor.tipo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=72,
)


_REQCONEXION = _descriptor.Descriptor(
  name='ReqConexion',
  full_name='problema2_2.ReqConexion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='problema2_2.ReqConexion.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tipo', full_name='problema2_2.ReqConexion.tipo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=113,
)


_REQSALUDO = _descriptor.Descriptor(
  name='ReqSaludo',
  full_name='problema2_2.ReqSaludo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='problema2_2.ReqSaludo.nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=142,
)


_RESCONEXION = _descriptor.Descriptor(
  name='ResConexion',
  full_name='problema2_2.ResConexion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='problema2_2.ResConexion.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conexion', full_name='problema2_2.ResConexion.conexion', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='conexiones', full_name='problema2_2.ResConexion.conexiones', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='problema2_2.ResConexion.mensaje', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=226,
)


_RESSALUDO = _descriptor.Descriptor(
  name='ResSaludo',
  full_name='problema2_2.ResSaludo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='saludo', full_name='problema2_2.ResSaludo.saludo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=255,
)

DESCRIPTOR.message_types_by_name['ReqServidor'] = _REQSERVIDOR
DESCRIPTOR.message_types_by_name['ReqConexion'] = _REQCONEXION
DESCRIPTOR.message_types_by_name['ReqSaludo'] = _REQSALUDO
DESCRIPTOR.message_types_by_name['ResConexion'] = _RESCONEXION
DESCRIPTOR.message_types_by_name['ResSaludo'] = _RESSALUDO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqServidor = _reflection.GeneratedProtocolMessageType('ReqServidor', (_message.Message,), {
  'DESCRIPTOR' : _REQSERVIDOR,
  '__module__' : 'servidor_n_pb2'
  # @@protoc_insertion_point(class_scope:problema2_2.ReqServidor)
  })
_sym_db.RegisterMessage(ReqServidor)

ReqConexion = _reflection.GeneratedProtocolMessageType('ReqConexion', (_message.Message,), {
  'DESCRIPTOR' : _REQCONEXION,
  '__module__' : 'servidor_n_pb2'
  # @@protoc_insertion_point(class_scope:problema2_2.ReqConexion)
  })
_sym_db.RegisterMessage(ReqConexion)

ReqSaludo = _reflection.GeneratedProtocolMessageType('ReqSaludo', (_message.Message,), {
  'DESCRIPTOR' : _REQSALUDO,
  '__module__' : 'servidor_n_pb2'
  # @@protoc_insertion_point(class_scope:problema2_2.ReqSaludo)
  })
_sym_db.RegisterMessage(ReqSaludo)

ResConexion = _reflection.GeneratedProtocolMessageType('ResConexion', (_message.Message,), {
  'DESCRIPTOR' : _RESCONEXION,
  '__module__' : 'servidor_n_pb2'
  # @@protoc_insertion_point(class_scope:problema2_2.ResConexion)
  })
_sym_db.RegisterMessage(ResConexion)

ResSaludo = _reflection.GeneratedProtocolMessageType('ResSaludo', (_message.Message,), {
  'DESCRIPTOR' : _RESSALUDO,
  '__module__' : 'servidor_n_pb2'
  # @@protoc_insertion_point(class_scope:problema2_2.ResSaludo)
  })
_sym_db.RegisterMessage(ResSaludo)



_DATA = _descriptor.ServiceDescriptor(
  name='Data',
  full_name='problema2_2.Data',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=258,
  serialized_end=546,
  methods=[
  _descriptor.MethodDescriptor(
    name='ServidorConexiones',
    full_name='problema2_2.Data.ServidorConexiones',
    index=0,
    containing_service=None,
    input_type=_REQSERVIDOR,
    output_type=_RESCONEXION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ConexionExitosa',
    full_name='problema2_2.Data.ConexionExitosa',
    index=1,
    containing_service=None,
    input_type=_REQCONEXION,
    output_type=_RESCONEXION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MSaludo',
    full_name='problema2_2.Data.MSaludo',
    index=2,
    containing_service=None,
    input_type=_REQSALUDO,
    output_type=_RESSALUDO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveConexion',
    full_name='problema2_2.Data.RemoveConexion',
    index=3,
    containing_service=None,
    input_type=_REQCONEXION,
    output_type=_RESCONEXION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATA)

DESCRIPTOR.services_by_name['Data'] = _DATA

# @@protoc_insertion_point(module_scope)
