# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Solicitudes.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Solicitudes.proto',
  package='practica5',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11Solicitudes.proto\x12\tpractica5\"!\n\x0esimple_Request\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\",\n\x07Request\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x10\n\x08mensaje2\x18\x02 \x01(\t\"\x1d\n\x08Response\x12\x11\n\trespuesta\x18\x01 \x01(\t\"?\n\x08Request2\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x10\n\x08mensaje2\x18\x02 \x01(\t\x12\x10\n\x08mensaje3\x18\x03 \x01(\t\"2\n\tResponse2\x12\x11\n\trespuesta\x18\x01 \x01(\t\x12\x12\n\nrespuesta2\x18\x02 \x01(\t\"Q\n\x08Request3\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x10\n\x08mensaje2\x18\x02 \x01(\t\x12\x10\n\x08mensaje3\x18\x03 \x01(\t\x12\x10\n\x08mensaje4\x18\x04 \x01(\t2\xe1\x04\n\x08\x43ommands\x12\x38\n\x04User\x12\x19.practica5.simple_Request\x1a\x13.practica5.Response\"\x00\x12=\n\x08Password\x12\x19.practica5.simple_Request\x1a\x14.practica5.Response2\"\x00\x12\x34\n\x06\x43reate\x12\x13.practica5.Request2\x1a\x13.practica5.Response\"\x00\x12\x32\n\x04Read\x12\x13.practica5.Request2\x1a\x13.practica5.Response\"\x00\x12\x33\n\x05Write\x12\x13.practica5.Request3\x1a\x13.practica5.Response\"\x00\x12\x34\n\x06Rename\x12\x13.practica5.Request2\x1a\x13.practica5.Response\"\x00\x12\x34\n\x06Remove\x12\x13.practica5.Request2\x1a\x13.practica5.Response\"\x00\x12\x33\n\x05MkDir\x12\x13.practica5.Request2\x1a\x13.practica5.Response\"\x00\x12\x33\n\x05RmDir\x12\x13.practica5.Request2\x1a\x13.practica5.Response\"\x00\x12\x36\n\x07ReadDir\x12\x12.practica5.Request\x1a\x13.practica5.Response\"\x00\x30\x01\x12/\n\x02\x43\x44\x12\x12.practica5.Request\x1a\x13.practica5.Response\"\x00\x62\x06proto3'
)




_SIMPLE_REQUEST = _descriptor.Descriptor(
  name='simple_Request',
  full_name='practica5.simple_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='practica5.simple_Request.mensaje', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=65,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='practica5.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='practica5.Request.mensaje', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mensaje2', full_name='practica5.Request.mensaje2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=111,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='practica5.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='respuesta', full_name='practica5.Response.respuesta', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=142,
)


_REQUEST2 = _descriptor.Descriptor(
  name='Request2',
  full_name='practica5.Request2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='practica5.Request2.mensaje', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mensaje2', full_name='practica5.Request2.mensaje2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mensaje3', full_name='practica5.Request2.mensaje3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=207,
)


_RESPONSE2 = _descriptor.Descriptor(
  name='Response2',
  full_name='practica5.Response2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='respuesta', full_name='practica5.Response2.respuesta', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='respuesta2', full_name='practica5.Response2.respuesta2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=259,
)


_REQUEST3 = _descriptor.Descriptor(
  name='Request3',
  full_name='practica5.Request3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='practica5.Request3.mensaje', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mensaje2', full_name='practica5.Request3.mensaje2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mensaje3', full_name='practica5.Request3.mensaje3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mensaje4', full_name='practica5.Request3.mensaje4', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=342,
)

DESCRIPTOR.message_types_by_name['simple_Request'] = _SIMPLE_REQUEST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Request2'] = _REQUEST2
DESCRIPTOR.message_types_by_name['Response2'] = _RESPONSE2
DESCRIPTOR.message_types_by_name['Request3'] = _REQUEST3
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

simple_Request = _reflection.GeneratedProtocolMessageType('simple_Request', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLE_REQUEST,
  '__module__' : 'Solicitudes_pb2'
  # @@protoc_insertion_point(class_scope:practica5.simple_Request)
  })
_sym_db.RegisterMessage(simple_Request)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'Solicitudes_pb2'
  # @@protoc_insertion_point(class_scope:practica5.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'Solicitudes_pb2'
  # @@protoc_insertion_point(class_scope:practica5.Response)
  })
_sym_db.RegisterMessage(Response)

Request2 = _reflection.GeneratedProtocolMessageType('Request2', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST2,
  '__module__' : 'Solicitudes_pb2'
  # @@protoc_insertion_point(class_scope:practica5.Request2)
  })
_sym_db.RegisterMessage(Request2)

Response2 = _reflection.GeneratedProtocolMessageType('Response2', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE2,
  '__module__' : 'Solicitudes_pb2'
  # @@protoc_insertion_point(class_scope:practica5.Response2)
  })
_sym_db.RegisterMessage(Response2)

Request3 = _reflection.GeneratedProtocolMessageType('Request3', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST3,
  '__module__' : 'Solicitudes_pb2'
  # @@protoc_insertion_point(class_scope:practica5.Request3)
  })
_sym_db.RegisterMessage(Request3)



_COMMANDS = _descriptor.ServiceDescriptor(
  name='Commands',
  full_name='practica5.Commands',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=345,
  serialized_end=954,
  methods=[
  _descriptor.MethodDescriptor(
    name='User',
    full_name='practica5.Commands.User',
    index=0,
    containing_service=None,
    input_type=_SIMPLE_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Password',
    full_name='practica5.Commands.Password',
    index=1,
    containing_service=None,
    input_type=_SIMPLE_REQUEST,
    output_type=_RESPONSE2,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='practica5.Commands.Create',
    index=2,
    containing_service=None,
    input_type=_REQUEST2,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='practica5.Commands.Read',
    index=3,
    containing_service=None,
    input_type=_REQUEST2,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='practica5.Commands.Write',
    index=4,
    containing_service=None,
    input_type=_REQUEST3,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Rename',
    full_name='practica5.Commands.Rename',
    index=5,
    containing_service=None,
    input_type=_REQUEST2,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Remove',
    full_name='practica5.Commands.Remove',
    index=6,
    containing_service=None,
    input_type=_REQUEST2,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MkDir',
    full_name='practica5.Commands.MkDir',
    index=7,
    containing_service=None,
    input_type=_REQUEST2,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RmDir',
    full_name='practica5.Commands.RmDir',
    index=8,
    containing_service=None,
    input_type=_REQUEST2,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadDir',
    full_name='practica5.Commands.ReadDir',
    index=9,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CD',
    full_name='practica5.Commands.CD',
    index=10,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMMANDS)

DESCRIPTOR.services_by_name['Commands'] = _COMMANDS

# @@protoc_insertion_point(module_scope)
